name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧱 Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.7" # Flutter stable sürüm

      - name: 📦 Install dependencies
        run: flutter pub get

      - name: 🏗️ Build Flutter web app
        run: flutter build web --release

      - name: 🔁 Copy Firebase config files
        run: |
          echo "📦 Copying Firebase config files..."
          if [ -f firebase.json ]; then cp firebase.json ./build/web/firebase.json; fi
          if [ -f .firebaserc ]; then cp .firebaserc ./build/web/.firebaserc; fi
          echo "✅ Files after copy:"
          ls -a ./build/web

      - name: 🚀 Deploy to Firebase Hosting
        uses: w9jds/firebase-action@v13.0.3
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: listed-prod-48501

